const translations = {
  en: {
    employees: "Employees",
    addNew: "Add New",
    edit: "Edit Employee",
    employeeList: "Employee List",
    firstName: "First Name",
    lastName: "Last Name",
    dateOfEmployement: "Date of Employment",
    dateOfBirth: "Date of Birth",
    phone: "Phone",
    email: "Email",
    department: "Department",
    position: "Position",
    actions: "Actions",
    search: "Search by first or last name",
    save: "Save",
    confirmDelete: "Are you sure?",
    deleteInfoLeft: "Selected Employee record of",
    deleteInfoRight: "will be deleted.",
    addEmployeeTitle: "Add Employee",
    editEmployeeTitle: "Edit Employee",
    formSubmitModalTitle: "Submit changes?",
    proceed: "Proceed",
    cancel: "Cancel",
    selectDepartment: "Select Department",
    selectPosition: "Select Position"
  },
  tr: {
    employees: "Çalışanlar",
    addNew: "Çalışan Ekle",
    edit: "Çalışanı Düzenle",
    employeeList: "Çalışan Listesi",
    firstName: "Ad",
    lastName: "Soyad",
    dateOfEmployement: "İşe Başlama Tarihi",
    dateOfBirth: "Doğum Tarihi",
    phone: "Telefon",
    email: "E-posta",
    department: "Departman",
    position: "Pozisyon",
    actions: "İşlemler",
    search: "Ad veya soyad arayın",
    save: "Kaydet",
    confirmDelete: "Emin misiniz?",
    deleteInfoLeft: "Seçilen",
    deleteInfoRight: "çalışan kaydı silinecek.",
    addEmployeeTitle: "Çalışan Ekle",
    editEmployeeTitle: "Çalışanı Düzenle",
    formSubmitModalTitle: "Değişiklikleri onaylıyor musunuz?",
    proceed: "Onayla",
    cancel: "İptal et",
    selectDepartment: "Departmanı seçin",
    selectPosition: "Pozisyonu seçin"
  },
};

export const translate = (key, lang = "en") => translations[lang]?.[key] || key;
